version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # For celery
      - "15672:15672" # RabbitMQ Dash

  worker:
    build: ./app
    container_name: celery_worker
    depends_on:
      - rabbitmq
    command: celery -A tasks worker --loglevel=info

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - rabbitmq
    command: python worker.py
